### ISSUE TITLE
not work in linux when behind proxy

### ISSUE THREAD

**Issue by prunith** [dermasmid/scrapetube#7]
Hi 
i m trying to use scrapetube on ubuntu 20.04 Python 3.8.10 behind company proxy setup-ed as follow:
`proxies = {"http": "http://x.x.253.137:80","https": "http://x.x.253.137:80"}`

scrapetube return:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/blairfancy/.local/lib/python3.8/site-packages/scrapetube/scrapetube.py", line 121, in get_search
    for video in videos:
  File "/home/blairfancy/.local/lib/python3.8/site-packages/scrapetube/scrapetube.py", line 138, in get_videos
    client = json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I suspect that proxy block connection.

**Comment by zhirshya** [comment]
I have similar problem, on ubuntu 20.04 with Python 3.
I set shell export HTTP_PROXY and HTTPS_PROXY.
Doing "scrapetube.get_channel" got
...line 7, in <module>
    for video in videos:
  File "/home/dvlpr/.local/lib/python3.8/site-packages/scrapetube/scrapetube.py", line 46, in get_channel
    for video in videos:
  File "/home/dvlpr/.local/lib/python3.8/site-packages/scrapetube/scrapetube.py", line 138, in get_videos
    client = json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
